workflows:
  app-store-release:
    name: Little Trip App Store
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.hanwaygo.gos
        APP_STORE_APPLE_ID: "6811079070"
        XCODE_PROJECT: LittleTrip.xcodeproj
        XCODE_SCHEME: LittleTrip
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Set build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          cd "$CM_BUILD_DIR"
          agvtool new-version -all $((LATEST_BUILD_NUMBER + 1))
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store: false
